/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import algoritmos.RoundRobin;
import estrutura.Arquivo;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import controlador.Controlador;

/**
 *
 * @author Gabriela
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    private File arquivo, diretorio;
    private String caminho;
    Controlador controlador;

    public Main() {
        diretorio = new File("/home/gabriela/Dropbox/Faculdade/8Periodo/SO/TP3/TP3_SO/TP3_SO/src/arquivoEntrada/");
        Controlador controlador;
        initComponents();
    }

    /**
     * @return o caminho do arquivo escolhido pelo usuário
     */
    public String caminhoArquivo() {
        Path path = null;
        JFileChooser abrirArquivo = new JFileChooser();
        abrirArquivo.setCurrentDirectory(diretorio);
        abrirArquivo.showOpenDialog(this);
        arquivo = abrirArquivo.getSelectedFile();

        try {
            path = Paths.get(arquivo.getAbsolutePath());

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao ler o arquivo!");
        }

        return path.toString();

    }
    
    public void executarAlgoritmoSelecionado(String algoritmo){
        
        switch(algoritmo){
            
            case "-":
                System.out.println("Wait");
            case "First Fit":
                System.out.println("First Fit");
//                controlador.executarFirstFit();
                break;
            case "Best Fit":
                System.out.println("Best Fit");
//                controlador.executarFirstFit();
                break;
            case "Next Fit":
                System.out.println("Next Fit");
//                controlador.executarNextFit();
                break;
            case "Quick Fit":
                System.out.println("Quick Fit");
//                controlador.executarQuickFit();
                break;
            case "Worst Fit":
                System.out.println("Worst Fit");
//                controlador.executarWorstFit();
                break;
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboAlgoritmo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gabriela - Trabalho Prático 3");

        jComboAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "First Fit", "Next Fit", "Best Fit", "Worst Fit", "Quick Fit" }));
        jComboAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlgoritmoActionPerformed(evt);
            }
        });

        jLabel1.setText("Escolha o algoritmo:");

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Carregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            caminho = this.caminhoArquivo();
            controlador = new Controlador(caminho);
        } catch (Exception e) {

        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jComboAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlgoritmoActionPerformed
        // TODO add your handling code here:
        String algoritmo = (String.valueOf(jComboAlgoritmo.getSelectedItem()));
        jComboAlgoritmo.setSelectedItem("-");
        this.executarAlgoritmoSelecionado(algoritmo);
//        controlador.executarAlgoritmoSelecionado(algoritmo);
    }//GEN-LAST:event_jComboAlgoritmoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboAlgoritmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
